import React from "react";
import { motion } from "framer-motion";
import { Helmet } from "react-helmet-async";
import { Mail } from "lucide-react";

export default function TermsOfUse() {
  return (
    <div className="bg-white min-h-screen">
      <Helmet>
        <title>Terms of Use | NuScript Health ZERA Scribe & ZERA RCM Clinical‑to‑Financial AI Platform</title>
        <meta name="description" content="Review NuScript Health's Terms of Use for the ZERA Scribe and ZERA RCM clinical‑to‑financial AI platform, including permitted use, clinical responsibility, intellectual property, interoperability, disclaimers, limitations of liability, governing law, and legal contact information." />
      </Helmet>
      {/* Hero */}
      <section className="relative pt-20 pb-12 lg:pt-32 lg:pb-16 bg-gradient-to-br from-blue-50 via-white to-indigo-50">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"
        >
          <div className="max-w-3xl">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-slate-900 mb-6">
              Terms of Use
            </h1>
            <p className="text-lg text-slate-600">
              Effective Date: August 14, 2025 (Updated January 16, 2026)
            </p>
          </div>
        </motion.div>
      </section>

      {/* Content */}
      <section className="py-12 lg:py-24 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mb-12"
          >
            <h2 className="text-2xl font-bold text-slate-900 mb-4">Introduction</h2>
            <p className="text-slate-600 leading-relaxed mb-8">
              Please read these Terms of Use ("Terms") carefully before using the website and services
              operated by NuScript Systems, Inc., doing business as NuScript Health ("NuScript Health",
              "we", "us", or "our"). By accessing or using our website and services, you agree to be bound
              by these Terms.
            </p>
          </motion.div>

          <div className="space-y-12">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-2xl font-bold text-slate-900 mb-4">1. Use of Our Services</h2>
              <p className="text-slate-600 leading-relaxed mb-4">
                Our services are intended for healthcare organizations and professionals seeking clinical
                documentation and revenue cycle support. You agree to use our services only for lawful
                purposes. You may not:
              </p>
              <ul className="space-y-4">
                {[
                  "Misuse or interfere with the functionality of our website or AI engines.",
                  "Attempt unauthorized access to our systems, data, or the RCM database.",
                  "Use our services for fraudulent activities or to bypass healthcare billing regulations."
                ].map((item, idx) => (
                  <li key={idx} className="flex gap-4">
                    <div className="flex-shrink-0">
                      <div className="flex items-center justify-center h-6 w-6 rounded-full bg-blue-100">
                        <span className="text-blue-600 text-sm font-semibold">•</span>
                      </div>
                    </div>
                    <div>
                      <p className="text-slate-600">{item}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-2xl font-bold text-slate-900 mb-4">2. Clinical and Professional Responsibility</h2>
              <p className="text-slate-600 leading-relaxed mb-4">
                NuScript Health provides administrative, documentation, and financial support tools through the ZERA™ AI Platform.
              </p>
              <ul className="space-y-4">
                {[
                  {
                    label: "No Medical Advice",
                    description: "Our services do not constitute medical advice, diagnosis, or treatment."
                  },
                  {
                    label: "Provider Responsibility",
                    description: "Clinicians maintain sole responsibility for the accuracy of clinical notes generated by ZERA™ Scribe. All medical decisions, patient care, and final billing submissions remain the professional responsibility of the User."
                  },
                  {
                    label: "Verification of AI Output",
                    description: "User acknowledges that ZERA™ Scribe and ZERA™ Flow utilize machine learning. You agree to review all AI-generated content and coding suggestions for accuracy before finalizing documentation or submitting claims."
                  }
                ].map((item, idx) => (
                  <li key={idx} className="flex gap-4">
                    <div className="flex-shrink-0">
                      <div className="flex items-center justify-center h-6 w-6 rounded-full bg-blue-100">
                        <span className="text-blue-600 text-sm font-semibold">•</span>
                      </div>
                    </div>
                    <div>
                      <h3 className="font-semibold text-slate-900 mb-1">{item.label}</h3>
                      <p className="text-slate-600">{item.description}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-2xl font-bold text-slate-900 mb-4">3. Intellectual Property and Proprietary Rights</h2>
              <p className="text-slate-600 leading-relaxed mb-4">
                All content on this website, including text, logos, graphics, and the underlying algorithms for ZERA™ Scribe and ZERA™ Flow, is the property of NuScript Systems, Inc.
              </p>
              <ul className="space-y-4">
                {[
                  {
                    label: "Restrictions",
                    description: "You are expressly prohibited from attempting to reverse engineer, decompile, or extract the source code or model weights of our AI products."
                  },
                  {
                    label: "Third-Party Marks",
                    description: "All product names (e.g., Epic, athenahealth, Oracle Cerner) are trademarks of their respective owners. Use of these names is for identification and interoperability description purposes only and does not imply endorsement or affiliation."
                  }
                ].map((item, idx) => (
                  <li key={idx} className="flex gap-4">
                    <div className="flex-shrink-0">
                      <div className="flex items-center justify-center h-6 w-6 rounded-full bg-blue-100">
                        <span className="text-blue-600 text-sm font-semibold">•</span>
                      </div>
                    </div>
                    <div>
                      <h3 className="font-semibold text-slate-900 mb-1">{item.label}</h3>
                      <p className="text-slate-600">{item.description}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-2xl font-bold text-slate-900 mb-4">4. Interoperability and Third-Party Integrations</h2>
              <p className="text-slate-600 leading-relaxed">
                Our services rely on integrations with third-party Electronic Health Record (EHR) systems and interoperability middleware. We are not liable for service interruptions, data synchronization errors, or downtime caused by these third-party platforms.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-2xl font-bold text-slate-900 mb-4">5. Disclaimers</h2>
              <p className="text-slate-600 leading-relaxed mb-4">
                Our services are provided "as is" and "as available." We do not warrant that:
              </p>
              <ul className="space-y-4">
                {[
                  "The website or AI generation will be 100% error-free or uninterrupted.",
                  "The services will guarantee specific financial outcomes or reimbursement rates.",
                  "Any AI-generated content is perfectly complete without human oversight."
                ].map((item, idx) => (
                  <li key={idx} className="flex gap-4">
                    <div className="flex-shrink-0">
                      <div className="flex items-center justify-center h-6 w-6 rounded-full bg-blue-100">
                        <span className="text-blue-600 text-sm font-semibold">•</span>
                      </div>
                    </div>
                    <div>
                      <p className="text-slate-600">{item}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-2xl font-bold text-slate-900 mb-4">6. Limitation of Liability</h2>
              <p className="text-slate-600 leading-relaxed">
                To the fullest extent permitted by law, NuScript Health shall not be liable for any indirect, incidental, or consequential damages (including loss of revenue or data) arising from your use of the platform. Our total liability shall not exceed the amount paid for the services in the six (6) months prior to the event giving rise to the claim.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
            >
              <h2 className="text-2xl font-bold text-slate-900 mb-4">7. Governing Law and Jurisdiction</h2>
              <p className="text-slate-600 leading-relaxed">
                These Terms are governed by the laws of the State of Texas. Any disputes shall be resolved in the state or federal courts located in Travis County, Texas, and you consent to the exclusive jurisdiction of such courts.
              </p>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              className="pt-8 border-t border-gray-200"
            >
              <h2 className="text-2xl font-bold text-slate-900 mb-8">8. Contact Information</h2>
              <div className="bg-gray-50 rounded-2xl p-8 border border-gray-200">
                <div className="space-y-6">
                  <div>
                    <p className="font-semibold text-slate-900 mb-2">NuScript Systems, Inc. dba NuScript Health</p>
                    <p className="text-slate-600">Attn: Legal Team</p>
                  </div>
                  <div className="flex items-center gap-3">
                    <Mail className="w-5 h-5 text-blue-600" />
                    <a
                      href="mailto:hello@nuscripthealth.com"
                      className="text-blue-600 hover:text-blue-700 font-medium"
                    >
                      hello@nuscripthealth.com
                    </a>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>
    </div>
  );
}